### ISSUE TITLE
还是经常出错

### ISSUE THREAD

**Issue by zeemars** [erma0/douyin#10]
在
`if self.type in ['post', 'like', 'follow', 'fans']:  # post页面需提取初始页面数据
            self.title = render_data['42']['user']['user']['nickname']
            self.info = render_data['42']['user']  # 备用`

原程序是41，我自己调试发现是42

还有编译后也不知到哪里有问题，exe不能运行，只能在vscode运行，没来的及调试

**Comment by erma0** [comment]
以前还是40呢，这个之前修复了，不过好像忘记推github了，回头编译了推一下
