### ISSUE TITLE
想请问如何爬取视频封面

### ISSUE THREAD

**Issue by GodeCAt** [erma0/douyin#15]
目前的代码爬取的封面并不是真正的封面，而是短视频的第一帧，想请问下有什么方法或接口能够爬取视频封面吗？

**Comment by erma0** [comment]
真正的封面指的是什么，接口返回数据在result目录下面，自己翻翻看，直接搜cover，有几个类似的字段

**Comment by GodeCAt** [comment]
真正的封面是指点进用户之后作品列表显示的封面，如下图。现在爬取用户是正确的封面，爬取单个视频的返回是视频的第一帧画面，我想请问的就是有没有只爬取单个视频返回值中包含真正的封面
![image](https://github.com/erma0/douyin/assets/98507651/dfad220e-16bf-4551-8573-dcfc0c8ab9cb)

**Comment by erma0** [comment]
pc端作品网页没有这个封面，用移动端可以获取，但是可能需要改动的内容较多，暂时不考虑加进来

**Comment by erma0** [comment]
试过了，用移动端浏览器能取到真正的封面，但是没有音乐信息，且返回的信息没有pc浏览器的全，所以暂不考虑改动。

暂不关闭此问题，等以后可能出现其他解决方案。
