### ISSUE TITLE
下载抖音用户白子画短视频拍摄出错

### ISSUE THREAD

**Issue by zhaozhifu0** [erma0/douyin#2]
![image](https://user-images.githubusercontent.com/14835443/225336904-41f3b3db-4de5-416f-8133-b93168759f55.png)
下载错误提示：
Exception caught
Exception: [download_helper.cc:562] errorCode=1 Failed to open the file .\下载\user_🔱, cause: File not found or it is a directory 在下载目录里有用户命名的下载列表文档，没有视频文件夹及文件。
附视频列表文档：
[user_🔱 白子画 短视频拍摄_MS4wLjABAAAAUe1jo5bYxPJybmnDDMxh2e9A95NAvoNfJiL7JVX5nhQ.txt](https://github.com/erma0/douyin/files/10980895/user_._MS4wLjABAAAAUe1jo5bYxPJybmnDDMxh2e9A95NAvoNfJiL7JVX5nhQ.txt)

**Comment by erma0** [comment]
应该是因为用户名表情符号没有过滤掉，等会看一下
