### ISSUE TITLE
老大,报错咋整-

### ISSUE THREAD

**Issue by peet2269** [erma0/douyin#21]
![360截图17430813205053](https://github.com/erma0/douyin/assets/116452440/4402327c-0fe0-4d29-a65c-09c1d26077a6)

**Comment by erma0** [comment]
改过代码吗，我打包的测试正常的啊，这是登录模块外部调用线程的问题

**Comment by peet2269** [comment]
没有改呢... 就windows的那俩程序,打开douyin.exe就报错闪退啦,难道是我浏览器的问题吗,这是打不开浏览器进行登录操作报错吧?

**Comment by erma0** [comment]
应该不是浏览器，是代码的问题，但是没道理我电脑正常你那边出现这个问题，同样的源码，运行逻辑一样的啊，等晚一点再看看吧，或者下次更新了你再试试，或者你直接跑源码看看调用堆栈












&nbsp;

**Comment by peet2269** [comment]
嗯嗯呐

**Comment by erma0** [comment]
dev分支内下载最新版测试，不行的话我也没办法，实在是因为问题无法复现

**Comment by peet2269** [comment]
啊哈哈哈确实不闪退了...,扫码登陆后输入网址出现
下图

关闭窗口再次输入网址就没反应了>.. 换了两台电脑,两台都是如此

**Comment by erma0** [comment]
这就奇怪了，我电脑上测试挺正常的。

可能还是代码有问题，issue先开着，等到看看有没有同样问题的吧。

**Comment by peet2269** [comment]
嗯嗯

**Comment by mydracula** [comment]
好像同问题
![image](https://github.com/erma0/douyin/assets/71320199/7b42870f-1df8-4f0b-8864-018d94d20944)

**Comment by erma0** [comment]
@mydracula 新版是0628，请用新版测试

**Comment by peet2269** [comment]
可以用啦,但是下载的文件夹乱码了

**Comment by peet2269** [comment]
谢谢,上次我估摸着是浏览器代理的问题
