### ISSUE TITLE
似乎因为反爬虫，当主页视频过多的时候，无法自动加载更多视频，每个主页只能采集19个视频或图文

### ISSUE THREAD

**Issue by FedoraLinux1** [erma0/douyin#26]
**运行环境：**

- 系统: Win10 
- 浏览器: msedge
- 使用方式: exe  

**问题描述：**

> 似乎因为反爬虫，当主页视频过多的时候，无法自动加载更多视频，每个主页只能采集19个视频或图文
> 本身在正常环境使用的浏览器中，加载更多视频的时候，也需要通过滑块或者文字顺序点击，才能加载出来

**Comment by erma0** [comment]
估计是官方更新了反爬，也有可能最近程序改动导致的问题，可以试试旧版，一样有问题的话就是反爬更新了，回头看看

**Comment by FedoraLinux1** [comment]
多次测试，反爬里应该是有检测“无痕模式”，改为{非无痕模式}后，大概率可以采集到全部视频，小概率需要手动验证

**Comment by erma0** [comment]
我测试发现替换成我本地浏览器ua就正常了，不清楚是不是playwright提供的ua有问题，你可以将browser文件75行注释去掉测试一下
