### ISSUE TITLE
login.py报错

### ISSUE THREAD

**Issue by zeemars** [erma0/douyin#27]
**运行环境：**

- 系统: Win11
- 浏览器:  msedge
- 使用方式: 源码

**运行命令：exec.py -u users.txt
> 请提供你运行的命令（主要是测试链接地址）以便复现问题

```
（例如：./douyin -u https://*/）

```

**问题描述：**

> 详细说明出现什么问题

刚开始登录时定义save_cookies提示错误

def save_cookies(cookies: list, key: list[str] = None):
报错：
发生异常: TypeError

'type' object is not subscriptable
  File "D:\codes\Douyin\login.py", line 33, in Login
    def save_cookies(cookies: list, key: list[str] = []):
  File "D:\codes\Douyin\login.py", line 6, in <module>
    class Login(object):
TypeError: 'type' object is not subscriptable

`这个错误是因为 list[str] = None 是一个语法错误。list[str] 意思是访问列表 list 的 str 键对应的值,但 str 不是一个整数索引,无法访问列表元素。所以会产生 TypeError: 'type' object is not subscriptable 错误。
要修复这个错误,应将默认参数 key 直接设置为 None,而不是 list[str] = None:
py
def save_cookies(cookies: list, key: list = None):  
将 key 的默认值直接设置为 None。
所以这个函数定义应修复为:
py
def save_cookies(cookies: list, key: list = None):  `

**Comment by erma0** [comment]
list[str]只是类型提示，不涉及代码逻辑，部分ide可能会有错误提示，但也不会影响程序运行，不知道你这个为什么报错，请自行排查原因

**Comment by zeemars** [comment]
现在还发现不能下载全部，只能下载刚开始加载出来的页面上的视频



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月24日(周六) 中午12:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [erma0/douyin] login.py报错 (Issue #27)




 
Closed #27 as completed.

**Comment by erma0** [comment]
参考#26 和https://gitee.com/erma0/douyin/pulls/1#note_19074875
也可以尝试更换browser文件的ua（好像是75行），或者拉取dev分支尝试，

**Comment by zeemars** [comment]
ok明白了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月27日(周二) 上午10:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [erma0/douyin] login.py报错 (Issue #27)




 
参考#26 和https://gitee.com/erma0/douyin/pulls/1#note_19074875
 也可以尝试更换browser文件的ua（好像是75行），或者拉取dev分支尝试，

**Comment by erma0** [comment]
> 'type' object is not subscriptable

不好意思，之前一直用的win11 python3.11没有报错过，这个问题今天在win10 python3.8复现了，原因是list没有大写，原理一样的，用做类型提示，dev分支已修复

**Comment by erma0** [comment]
另外，我换ua本地测试就能正常采集，建议测试一下新版

**Comment by zeemars** [comment]
奥，明白了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 下午2:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [erma0/douyin] login.py报错 (Issue #27)




  
'type' object is not subscriptable
  
不好意思，之前一直用的win11 python3.11没有报错过，这个问题今天在win10 python3.8复现了，原因是list没有大写，原理一样的，用做类型提示，dev分支已修复

**Comment by zeemars** [comment]
OK好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 下午2:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [erma0/douyin] login.py报错 (Issue #27)




 
另外，我换ua本地测试就能正常采集，建议测试一下新版
