### ISSUE TITLE
API.py入口是哪个

### ISSUE THREAD

**Issue by 2478641181** [erma0/douyin#29]
如何用API.py搭建一个接口

**Comment by erma0** [comment]
直接运行，然后访问/docs看文档。代码写的比较乱，一时半会我也说不清楚

**Comment by 2478641181** [comment]
本地部署成功 127.0.0.1:567也通 但是项目貌似会调用自带浏览器 我部署到宝塔面板后 使用接口返回 Internal Server Error
大佬考虑换个网络访问的库吗？
![image](https://github.com/erma0/douyin/assets/92560664/8e40c237-860e-46fd-99d3-d5a824530b5d)
![image](https://github.com/erma0/douyin/assets/92560664/19de8b90-40d2-4fe7-9879-e7bb7ac26cff)

**Comment by erma0** [comment]
由于直接发包涉及js解密（原v2分支时无需解密），所以v3分支才基于本地浏览器开发，暂不考虑更改。


纯网络请求可以考虑其他类似程序，github有开源的成品js解密和接口，类似的爬虫应该不少的










&nbsp;

**Comment by 2478641181** [comment]
意思是我现在部署v2或者找其他的爬虫？

**Comment by erma0** [comment]
v2早失效了，我意思是直接找别的











&nbsp;

**Comment by nicktzp** [comment]
![image](https://github.com/erma0/douyin/assets/53168458/228327f3-0e87-427d-89e7-ea1d1193bff0)
本地地址也是报 Internal Server Error，好像用不起来，用的最新的版本。
