### ISSUE TITLE
老大，有空看一下报错是怎么回事

### ISSUE THREAD

**Issue by 0416zhang** [erma0/douyin#30]
命令：douyin -t post -u https://v.douyin.com/ia7kMcG/
系统：Windows 11
报错内容：requests.exceptions.SSLError: HTTPSConnectionPool(host='v.douyin.com', port=443): Max retries exceeded with url: /iaWnRyC (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))
[19128] Failed to execute script 'exec' due to unhandled exception!

**Comment by bxiaoj** [comment]
[video-parser](https://github.com/bxiaoj/video-parser/), may be able to help you solve the problem, worth trying.
