### ISSUE TITLE
运行结果出问题

### ISSUE THREAD

**Issue by Robin-Teng** [erma0/douyin#31]
**运行环境：**

- 系统: Win10 
- 浏览器: Chrome 
- 使用方式: exe  

**运行命令：**
直接运行douyin.exe，输入抖音网页URL，运行

**问题描述：**

显示爬取成功，点开结果发现视频全是0字节，根本没有下载成功。

**Comment by bxiaoj** [comment]
[video-parser](https://github.com/bxiaoj/video-parser/), may be able to help you solve the problem, worth trying.

**Comment by yancheng17** [comment]
可以支持播放量吗，我看有的视频可以查看播放量，在awe这个文件中，目前只了解到合集的播放量是百分比可以破解的，合集之外的视频播放量要如何破解

**Comment by qzzhujixue** [comment]
大佬，咋解决的，我前一天还好好的，第二天图片能下载，视频是0KB，被封了？

**Comment by yancheng17** [comment]
你是什么样的，什么问题，有截图吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "erma0/douyin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 晚上6:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [erma0/douyin] 运行结果出问题 (Issue #31)





 
大佬，咋解决的，我前一天还好好的，第二天图片能下载，视频是0KB，被封了？
