### ISSUE TITLE
关键词爬虫报错

### ISSUE THREAD

**Issue by zcunyi** [erma0/douyin#37]
![image](https://github.com/user-attachments/assets/0509d0b7-7f9a-42b6-8a90-9483d6fed3e4)

**Comment by erma0** [comment]
需要指定类型 -t search 
![111111](https://github.com/user-attachments/assets/a53d4bd3-b973-483f-9dd6-4778a5e2ac07)

**Comment by zcunyi** [comment]
> 需要指定类型 -t search ![111111](https://private-user-images.githubusercontent.com/76248124/348701510-a53d4bd3-b973-483f-9dd6-4778a5e2ac07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTQxMTUsIm5iZiI6MTcyMTA1MzgxNSwicGF0aCI6Ii83NjI0ODEyNC8zNDg3MDE1MTAtYTUzZDRiZDMtYjk3My00ODNmLTlkZDYtNDc3OGE1ZTJhYzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjODEyNGM3ZWYxNzUzMmJkNTA3ZTcxMGQ4NzE3MjhjNTgwYzFiMTcwNjNiOWU3NzI1ZGUwMzg3YWE1MmNiMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jawjaFtfLM-9z_F1R_BTgiiNQPO-piprxqFT0YDPPJ4)

增加了-t search 依然有同样的报错
