### ISSUE TITLE
采集单个作品成功，主页作品，没成功

### ISSUE THREAD

**Issue by iapeng** [erma0/douyin#38]
主页地址
https://v.douyin.com/iMRySUBx/

**Comment by erma0** [comment]
测试正常，请检查cookie，参考 https://github.com/erma0/douyin?tab=readme-ov-file#%E8%8E%B7%E5%8F%96cookie

![image](https://github.com/user-attachments/assets/909644ec-1bfa-494b-8d20-a8bfe3b8a309)
