### ISSUE TITLE
采集请求出错

### ISSUE THREAD

**Issue by BlueSkyLT** [erma0/douyin#39]
**运行环境：**

- 系统: Win10 
- 使用方式: Python / exe  

**运行命令：**
> 请提供你运行的命令（主要是提供测试链接地址）以便复现问题

```
douyin.exe -u https://v.douyin.com/iMRySUBx/

```

**问题描述：**

不太熟悉爬虫和网络，不确定是不是配置正确

采集请求出错...
![image](https://github.com/user-attachments/assets/47e9ffc6-e5ac-45ec-a31c-26c60e0e005e)

------------
另外`cookie.txt`是应该保存在`./config`下面还是`./dist/config`下面？我看`./dist/config`里面已经有`cookie.json`了

**Comment by erma0** [comment]
![image](https://github.com/user-attachments/assets/182ee208-4511-416d-8d64-05e79c17a57e)
测试没问题的，出错的原因可能是你填的Cookie无效

> 另外cookie.txt是应该保存在./config下面还是./dist/config下面？

就是运行程序的相对路径的./config下面，你运行Python源码那就是./config，你运行./dist/douyin.exe那就是在./dist/config，也就是相对于exe程序来说还是./config下面

> 我看./dist/config里面已经有cookie.json了

因为你运行中手动填过一次Cookie或者从浏览器自动获取过一次Cookie，之后就会自动保存下来
