### ISSUE TITLE
粉丝无法采集

### ISSUE THREAD

**Issue by Suz1e** [erma0/douyin#40]
**运行环境：**

- 系统: Win11
- 使用方式: Python

**运行命令：**

```
-t fans

```

**问题描述：**
目标输入错误，请检查参数
![QQ截图20240728160044](https://github.com/user-attachments/assets/8f50c70a-cf79-4a9e-9ad9-e21ec4e992d2)

**Comment by erma0** [comment]
再看看使用说明，./douyin -t fans

**Comment by Suz1e** [comment]
> 再看看使用说明，./douyin -t fans

用这个指令也报错，我试过的
![QQ截图20240731151217](https://github.com/user-attachments/assets/e5c7c8df-566b-40b6-ba9f-175dfe028c5a)

**Comment by erma0** [comment]
仔细看看使用说明，不是在这里输入的。。。是打开命令行直接输入命令

**Comment by Suz1e** [comment]
> 仔细看看使用说明，不是在这里输入的。。。是打开命令行直接输入命令

我也试了 也不行
