### ISSUE TITLE
通过地址下载视频时候有些链接无法下载

### ISSUE THREAD

**Issue by heyianle** [erma0/douyin#41]
**运行环境：**

- 系统: Win10
- 使用方式: Python3.12 和 exe  

**运行命令：**
> 请提供你运行的命令（主要是提供测试链接地址）以便复现问题
> 链接地址
例如
https://www.douyin.com/video/7395182828473847091
https://www.douyin.com/video/7394432088059022630
https://www.douyin.com/video/7393803711774067979
https://www.douyin.com/video/7393803716924640553

**问题描述：**

> 详细说明出现什么问题
> 日志输出
2024-07-30 22:54:41.587 | INFO     | douyin:__append_awemes:450 - 采集中，已采集到1条结果
2024-07-30 22:54:41.588 | SUCCESS  | douyin:save:502 - 采集完成，本次共采集到1条结果
2024-07-30 22:54:41.593 | INFO     | utils.download:download:12 - 开始下载
None

07/30 22:54:41 [ERROR] CUID#7 - Download aborted. URI=https://www.douyin.com/aweme/v1/play/?video_id=v02033g10000cqe1gq7og65vnkupe0e0&line=0&ratio=540p&watermark=0&media_type=4&vr_type=0&improve_bitrate=0&biz_sign=NRPI1lC4AlkgB1YZ_o3Jx_AcRCRKvePEcuHSo48zZSqwTcZpH5dahdoSorGE9VaaOzLa7CA0Ou-V1V2BgV0QftMS70fFDGbNHaUZIZuaRMUGyO7s5wbVW7et0I2xs1hA&logo_name=aweme_search_suffix&source=PackSourceEnum_AWEME_DETAIL
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://www.douyin.com/aweme/v1/play/?video_id=v02033g10000cqe1gq7og65vnkupe0e0&line=0&ratio=540p&watermark=0&media_type=4&vr_type=0&improve_bitrate=0&biz_sign=NRPI1lC4AlkgB1YZ_o3Jx_AcRCRKvePEcuHSo48zZSqwTcZpH5dahdoSorGE9VaaOzLa7CA0Ou-V1V2BgV0QftMS70fFDGbNHaUZIZuaRMUGyO7s5wbVW7et0I2xs1hA&logo_name=aweme_search_suffix&source=PackSourceEnum_AWEME_DETAIL
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8d4d75|ERR |       0B/s|./下载/video_7393811463112035593/7393811463112035593_衣服掉色怎么办，快来试试这款固色神器，让你的衣服焕然一新#衣物固色剂 #好物分享 #固色剂.mp4

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by erma0** [comment]
不知道为什么这类链接通过网页源码获取到的视频地址不能正常下载，其他链接下载失败的原因都是403，这个直接是无响应。
现在切换到api获取了，测试能够下载，可以重新尝试一下

**Comment by heyianle** [comment]
可以，这种链接没找出有什么其它异常，就是访问不到

**Comment by heyianle** [comment]
感谢！
