### ISSUE TITLE
粉丝数据抓取问题

### ISSUE THREAD

**Issue by nicktzp** [erma0/douyin#42]
抓取粉丝数据，但是基本上每次抓取几十个后就不行了，更换cookie 也不行，第二天又可以抓几十个，这个是触发风控了吗？

**Comment by erma0** [comment]
现在是能抓一个账号的几十个粉丝 还是抓几十个账号的全部粉丝？

**Comment by nicktzp** [comment]
通过这个命令抓的：  Douyin(target=douyin_id, type='user', limit=1)

抓几十个账号本身的粉丝个数（并不抓取每个账号的全部粉丝）
例如： 抓取人民日报有多少个粉丝，新华社有多少个粉丝。


***@***.***
 
发件人： 二毛
发送时间： 2024-07-31 23:12
收件人： erma0/douyin
抄送： nicktzp; Author
主题： Re: [erma0/douyin] 粉丝数据抓取问题 (Issue #42)
现在是能抓一个账号的几十个粉丝 还是抓几十个账号的全部粉丝？

**Comment by erma0** [comment]
如果只是查账号信息的话，源码里面有个v2的user info 接口可以直接用，稍微改一下就可以批量查了












&nbsp;
