### ISSUE TITLE
粉丝采集出错

### ISSUE THREAD

**Issue by Suz1e** [erma0/douyin#43]
提取到一半无法提取了，似乎是需要添加延迟
![QQ截图20240805194144](https://github.com/user-attachments/assets/67a95e3b-3ac1-4af6-9d70-dfda4ee23a4e)

**Comment by erma0** [comment]
可能采集量大就会触发风控吧，直接ban了IP也说不定，延迟会影响效率，暂时不考虑加入，可以自行添加延迟测试一下

**Comment by Suz1e** [comment]
> 可能采集量大就会触发风控吧，直接ban了IP也说不定，延迟会影响效率，暂时不考虑加入，可以自行添加延迟测试一下

是的，我添加了延迟好很多了，我发现json文件中会有很多的i，比如sec_uid、uid、short_id、unique_id，这里面哪个ID是系统默认的且不会改变的ID？

**Comment by erma0** [comment]
sec_uid和uid都不会变，现在的接口也基本都是用sec_uid











&nbsp;
