### ISSUE TITLE
话题播放量采集

### ISSUE THREAD

**Issue by nicktzp** [erma0/douyin#44]
请问有没有办法采集到指定关键字的话题播放量？
![111](https://github.com/user-attachments/assets/db479a73-9724-4dab-ba3d-e2d5e3b12513)

**Comment by erma0** [comment]
想一步到位就需要APP接口了，因为网页版没有话题的入口

不过也可以迂回一下，从搜索接口找 到关键词的hash_id，再通过这个ID去查询播放信息，理论上可行

**Comment by nicktzp** [comment]
请问具体哪个搜索接口可以找到这个hash_id啊？ 没找到这个。谢谢！

**Comment by erma0** [comment]
就是视频搜索，然后筛选关键字，拿到关键字对应的hash_id
