### ISSUE TITLE
搜索作品接口，可以选最多点赞排序搜索吗

### ISSUE THREAD

**Issue by fggzs** [erma0/douyin#45]
搜索作品接口，可以选最多点赞排序搜索吗

**Comment by erma0** [comment]
![image](https://github.com/user-attachments/assets/4f7d98ae-463e-4895-a1b7-c8367bd90368)
源码这里可以改，不过  现在的不是按最多点赞排序吗，那现在是什么排序，有测试吗

**Comment by fggzs** [comment]
我用的之前的版本，我更新一下

**Comment by fggzs** [comment]
![image](https://github.com/user-attachments/assets/b682c9d7-04ab-4ed6-91a0-d27e60ce5c85)
更到最新了，填的300，只有93条数据，之前旧的一次搜索有200多条。这是哪里限制了吗？

**Comment by erma0** [comment]
之前的版本是哪个版本，我对比一下

**Comment by fggzs** [comment]
你README里面没有写版本，只能看代码对比了
![image](https://github.com/user-attachments/assets/6798fea6-6320-48bd-b1e2-5dc570aa1074)

**Comment by longabc12** [comment]
which api to get all users video bro , i just know your repo

> Which version was the previous one? I'll compare it.

**Comment by erma0** [comment]
> 你README里面没有写版本，只能看代码对比了

看着像v3分支里面的，用playwright的版本，很久没更新了，现在还能用？我印象中这个版本风控严重不能用了来着

**Comment by erma0** [comment]
> which api to get all users video bro , i just know your repo

aweme/v1/web/aweme/post
![image](https://github.com/user-attachments/assets/6387d6cc-7204-457d-ab61-b700610a830c)

**Comment by fggzs** [comment]
![image](https://github.com/user-attachments/assets/defb0e1e-a3b2-4f16-b91d-b49de0abb6ac)
找到版本了，这个版本没有douyin.py这个文件

**Comment by erma0** [comment]
> 找到版本了，这个版本没有douyin.py这个文件

是的，v3实现原理不一样，就是模拟浏览器点击加上拦截网页请求数据，现在的版本是重写了的。
话说我一直以为失效了来着，你想实现筛选的话就要在代码里加一个模拟点击筛选的步骤就行了。
