### ISSUE TITLE
抖音更新了吗，现在好像不行了

### ISSUE THREAD

**Issue by dugumoss** [erma0/douyin#47]
9月8号时试过，是OK的。可以成功下载某个用户的作品
今天尝试不行了。

出错信息是这样：

pattern = r'self\.__pace_f\.push\(\[1,"\d:\[\S+?({[\s\S]*?)\]\\n"\]\)</script>'
render_data: str = re.findall(pattern, text)[-1]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

应该是这个正则解析错误

**Comment by erma0** [comment]
那应该是更新了，回头有时间看看











&nbsp;

**Comment by erma0** [comment]
刚刚测试了一下，我这还正常的啊，链接发来我试试？
