### ISSUE TITLE
有傻瓜教程吗

### ISSUE THREAD

**Issue by Cheng999992** [erma0/douyin#48]
**运行环境：**

- 系统: Win10 / Win11 / Linux
- 使用方式: Python / exe  

**运行命令：**
> 请提供你运行的命令（主要是提供测试链接地址）以便复现问题

```
（例如：./douyin -u https://*/）

```

**问题描述：**
一直是这样 只写过java 这个刚看到不知道咋弄 麻烦作者大大
> 详细说明出现什么问题
![image](https://github.com/user-attachments/assets/9d64a838-0f5e-4d4e-ae78-278efb957b36)

**Comment by erma0** [comment]
双击运行，直接输入链接
