### ISSUE TITLE
无法爬取一个用户所有视频

### ISSUE THREAD

**Issue by GodeCAt** [erma0/douyin#6]
作者您好，我使用您的代码，之前是可以爬取所有视频的，但是抖音更新后似乎无法通过原来cursor的更新方法来爬取一个用户后面的视频，会出现无论cursor是多少，总会爬取前面用户前面几个视频的情况，请问这个能够怎么解决呢？
![image](https://user-images.githubusercontent.com/98507651/233833271-97f6a92b-1234-4d73-a54c-0fa081265b79.png)
![image](https://user-images.githubusercontent.com/98507651/233833367-8ea0f218-83bd-4c49-8ee1-65f82dd652ee.png)

**Comment by GodeCAt** [comment]
我测试了一下，发现参数传不进去，不管输入的cursor是多少，返回的max_cursor和min_cursor都是一样的，对结果没影响

**Comment by GodeCAt** [comment]
请问如何与您联系？

**Comment by erma0** [comment]
> 我测试了一下，发现参数传不进去，不管输入的cursor是多少，返回的max_cursor和min_cursor都是一样的，对结果没影响

我试了一下，是爬不全，但也不是只爬前面几个视频，大概能爬80%就结束了，不知道怎么更新的，没时间细看，但是没有发现你说的这个“返回的max_cursor和min_cursor都是一样的”问题，如果是你说的这个问题，那就没办法了，那就是后端不接受参数了，如果是返回的cursor不准还可以根据上一次返回的作品信息来手动更新cursor。

还可以采用另一种方法来爬数据，不会有这些更新的烦恼，之前心血来潮还想做一个呢，但是又搁置了，有兴趣你可以试试，用无头浏览器拦截返回的作品列表，无限下滑屏幕即可取回数据。

**Comment by GodeCAt** [comment]
谢谢博主，我说的max_cursor和min_cursor一样是指在用原来的方法爬一个用户时，每次返回的包含aweme_list的数据中的max_cursor和min_cursor不会改变，也就是不管传入的max_cursor是多少，都会出现相同的返回数据

**Comment by erma0** [comment]
我懂你意思，爬话题的时候也没有返回cursor的，但是可以手动更新提交cursor的，能正常取回数据。

但是我昨天测试几个账号是都可以正常返回80%左右的数据的，每个账号爬到的作品数量不一样，没细看是缺的哪一部分数据，因为没有报错，只是数据少了，所以不太好比对。

你测试的是所有账号都只能爬前面十几个或者几十个吗？还是和我一样，缺一部分数据？

**Comment by GodeCAt** [comment]
我测试的是，爬取用户时，不管是手动还是自动获取cursor作为参数传进去，每次返回的aweme_list是相同的数据，一个aweme_list中有15条视频数据，所以如果limit是30，那就是15条数据重复2次，如果limit是45，那就是15条数据重复3次。

**Comment by GodeCAt** [comment]
我测试的是，爬取用户时，不管是手动还是自动获取cursor作为参数传进去，每次返回的aweme_list是相同的数据，一个aweme_list中有15条视频数据，所以如果limit是30，那就是15条数据重复2次，如果limit是45，那就是15条数据重复3次。

**Comment by erma0** [comment]
那就和我这测试结果也不一样，我测试的好歹还能爬80%的数据呢。

这个因为是用的移动端网页接口，现在应该是后端限制了，只给15条数据，那就没办法了，要改用PC端接口，但是PC接口又需要解密，还是用无头浏览器比较简单，一劳永逸，没事的时候研究一下吧

**Comment by GodeCAt** [comment]
谢谢博主

**Comment by erma0** [comment]
已更新
