### ISSUE TITLE
抖音关注

### ISSUE THREAD

**Issue by WoAiNianChu** [erma0/douyin#7]
你好，未来有打算出一个采集指定人的关注列表，然后输出到文件里的功能吗？

**Comment by erma0** [comment]
只需要关注的人信息还是要挨个采集作品？加进去应该也不太麻烦，可以考虑。但如果只需要关注列表信息的话，其实后裔采集器这一类的工具就能做了。

**Comment by WoAiNianChu** [comment]
> 只需要关注的人信息还是要挨个采集作品？ 加进去应该也不太麻烦，可以考虑。 但如果只需要关注列表信息的话，其实后裔采集器这一类的工具就能做了。

在公开关注列表的情况下，只需要采集关注列表的昵称然后输出到文本文件就行，更详细(简介，性别之类的)当然更好。

**Comment by erma0** [comment]
已更新，支持采集关注/粉丝列表
